/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchDonorsRouteImport } from './routes/search-donors'
import { Route as RecipientRegisterRouteImport } from './routes/recipient-register'
import { Route as RecipientLoginRouteImport } from './routes/recipient-login'
import { Route as DonorRegisterRouteImport } from './routes/donor-register'
import { Route as DonorLoginRouteImport } from './routes/donor-login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SearchDonorsRoute = SearchDonorsRouteImport.update({
  id: '/search-donors',
  path: '/search-donors',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipientRegisterRoute = RecipientRegisterRouteImport.update({
  id: '/recipient-register',
  path: '/recipient-register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipientLoginRoute = RecipientLoginRouteImport.update({
  id: '/recipient-login',
  path: '/recipient-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorRegisterRoute = DonorRegisterRouteImport.update({
  id: '/donor-register',
  path: '/donor-register',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorLoginRoute = DonorLoginRouteImport.update({
  id: '/donor-login',
  path: '/donor-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donor-login': typeof DonorLoginRoute
  '/donor-register': typeof DonorRegisterRoute
  '/recipient-login': typeof RecipientLoginRoute
  '/recipient-register': typeof RecipientRegisterRoute
  '/search-donors': typeof SearchDonorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donor-login': typeof DonorLoginRoute
  '/donor-register': typeof DonorRegisterRoute
  '/recipient-login': typeof RecipientLoginRoute
  '/recipient-register': typeof RecipientRegisterRoute
  '/search-donors': typeof SearchDonorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donor-login': typeof DonorLoginRoute
  '/donor-register': typeof DonorRegisterRoute
  '/recipient-login': typeof RecipientLoginRoute
  '/recipient-register': typeof RecipientRegisterRoute
  '/search-donors': typeof SearchDonorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/donor-login'
    | '/donor-register'
    | '/recipient-login'
    | '/recipient-register'
    | '/search-donors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/donor-login'
    | '/donor-register'
    | '/recipient-login'
    | '/recipient-register'
    | '/search-donors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/donor-login'
    | '/donor-register'
    | '/recipient-login'
    | '/recipient-register'
    | '/search-donors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DonorLoginRoute: typeof DonorLoginRoute
  DonorRegisterRoute: typeof DonorRegisterRoute
  RecipientLoginRoute: typeof RecipientLoginRoute
  RecipientRegisterRoute: typeof RecipientRegisterRoute
  SearchDonorsRoute: typeof SearchDonorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search-donors': {
      id: '/search-donors'
      path: '/search-donors'
      fullPath: '/search-donors'
      preLoaderRoute: typeof SearchDonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipient-register': {
      id: '/recipient-register'
      path: '/recipient-register'
      fullPath: '/recipient-register'
      preLoaderRoute: typeof RecipientRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipient-login': {
      id: '/recipient-login'
      path: '/recipient-login'
      fullPath: '/recipient-login'
      preLoaderRoute: typeof RecipientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor-register': {
      id: '/donor-register'
      path: '/donor-register'
      fullPath: '/donor-register'
      preLoaderRoute: typeof DonorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor-login': {
      id: '/donor-login'
      path: '/donor-login'
      fullPath: '/donor-login'
      preLoaderRoute: typeof DonorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DonorLoginRoute: DonorLoginRoute,
  DonorRegisterRoute: DonorRegisterRoute,
  RecipientLoginRoute: RecipientLoginRoute,
  RecipientRegisterRoute: RecipientRegisterRoute,
  SearchDonorsRoute: SearchDonorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
